import 'package:planet_community/entity/planet_entity.dart';
import 'package:planet_community/source/images.dart';

var baseUrl = 'https://my-json-server.typicode.com/DmGurin/planet_community/';

List<PlanetEntity> planetList = [
  PlanetEntity(
    name: 'MARS',
    largeImage: AppImages.bigmars,
    image: AppImages.mars,
    minTemp: '2',
    maxTemp: '20',
    minQuake: '3',
    maxQuake: '4',
    typePlanet: 'THE RED PLANET',
    redus: '3,389.5',
    moons: 'PHOBOS, DEIMOS',
    distance: '229.23 MILLION',
    period: '639 DAYS',
  ),
  PlanetEntity(
    name: 'EARTH',
    largeImage: AppImages.bigearth,
    image: AppImages.earth,
    minTemp: '0',
    maxTemp: '40',
    minQuake: '1',
    maxQuake: '6',
    typePlanet: 'THE LIVING PLANET',
    redus: '6378.1',
    moons: 'MOON',
    distance: '147.12 MILLION',
    period: '361 DAYS',
  ),
  PlanetEntity(
    name: 'JUPITER',
    largeImage: AppImages.bigjupiter,
    image: AppImages.jupiter,
    minTemp: '50',
    maxTemp: '100',
    minQuake: '2',
    maxQuake: '5',
    typePlanet: 'THE GAS PLANET',
    redus: '69,911',
    moons: '79 MOONS',
    distance: '746.89 MILLION',
    period: '12 YEARS',
  ),
  PlanetEntity(
    name: 'URANUS',
    largeImage: AppImages.biguranus,
    image: AppImages.uranus,
    minTemp: '0',
    maxTemp: '20',
    minQuake: '1',
    maxQuake: '3',
    typePlanet: 'THE COOLED PLANET',
    redus: '25,362',
    moons: '27 MOONS',
    distance: '2.9496 BILLION',
    period: '84 YEARS',
  ),
  PlanetEntity(
    name: 'VENUS',
    largeImage: AppImages.bigvenus,
    image: AppImages.venus,
    minTemp: '50',
    maxTemp: '150',
    minQuake: '8',
    maxQuake: '9',
    typePlanet: 'GOLWING PLANET',
    redus: '6,051.8',
    moons: '0 MOONS',
    distance: '107.1 MILLION',
    period: '225 DAYS',
  ),
];

final List<String> imgList = [
  'assets/images/mars.png',
  'assets/images/earth.png',
  'assets/images/jupiter.png',
  'assets/images/uranus.png',
  'assets/images/venus.png',
];
